{ pkgs }: {
  deps = [
    pkgs.haskellPackages.data-default-instances-unordered-containers
    pkgs.home-assistant-component-tests.application_credentials
    pkgs.haskellPackages.data-default-instances-containers
    pkgs.rPackages.AustralianPoliticians
    pkgs.perlPackages.CatalystAuthenticationStoreHtpasswd
    pkgs.perl534Packages.CatalystAuthenticationStoreLDAP
    pkgs.haskellPackages.amazonka-marketplace-analytics
    pkgs.perl536Packages.CatalystAuthenticationStoreDBIxClass
    pkgs.perlPackages.CatalystAuthenticationStoreDBIxClass
    pkgs.perl534Packages.CatalystAuthenticationStoreHtpasswd
    pkgs.perl536Packages.CatalystAuthenticationStoreHtpasswd
    pkgs.perlPackages.CatalystAuthenticationStoreLDAP
    pkgs.perl534Packages.CatalystAuthenticationStoreDBIxClass
    pkgs.perl536Packages.CatalystAuthenticationStoreLDAP
    pkgs.python311Packages.azure-mgmt-datalake-analytics
    pkgs.python310Packages.azure-mgmt-datalake-analytics
    pkgs.python311Packages.azure-mgmt-loganalytics
    pkgs.python310Packages.azure-mgmt-loganalytics
    pkgs.matrix-synapse-plugins.matrix-synapse-mjolnir-antispam
    pkgs.atlantis
    pkgs.haskellPackages.JunkDB-driver-hashtables
    pkgs.htmlunit-driver
    pkgs.rPackages.Runiversal
    pkgs.perl534Packages.UNIVERSALisa
    pkgs.perl534Packages.UNIVERSALrequire
    pkgs.perl536Packages.UNIVERSALisa
    pkgs.perl536Packages.UNIVERSALrequire
    pkgs.perlPackages.UNIVERSALrequire
    pkgs.perl536Packages.UNIVERSALcan
    pkgs.perlPackages.UNIVERSALcan
    pkgs.perlPackages.UNIVERSALisa
    pkgs.perl534Packages.UNIVERSALcan
    pkgs.rPackages.universals
    pkgs.gnomeExtensions.hide-universal-access
    pkgs.rPackages.universalmotif
    pkgs.base16-universal-manager
    pkgs.nix-universal-prefetch
    pkgs.home-assistant-component-tests.universal
    pkgs.sbclPackages.universal-config
    pkgs.haskellPackages.universal-binary
    pkgs.universal-ctags
    pkgs.emacsPackages.universal-emotions-emoticons
    pkgs.haskellPackages.universal
    pkgs.gnomeExtensions.control-blur-effect-on-lock-screen
    pkgs.sbclPackages.cl-glfw-opengl-ext__framebuffer__multisample
    pkgs.haskellPackages.perfect-vector-shuffle
    pkgs.trufflehog
    pkgs.python311Packages.google-cloud-texttospeech
    pkgs.python311Packages.google-cloud-container
    pkgs.python311Packages.google-cloud-iam-logging
    pkgs.python310Packages.googleapis-common-protos
    pkgs.python310Packages.google-cloud-bigquery
    pkgs.python310Packages.google-cloud-iam
    pkgs.python310Packages.google-compute-engine
    pkgs.python310Packages.google-cloud-resource-manager
    pkgs.python310Packages.google-cloud-core
    pkgs.python311Packages.google-api-python-client
    pkgs.python311Packages.google-reauth
    pkgs.python310Packages.google-crc32c
    pkgs.python311Packages.google-cloud-datacatalog
    pkgs.python310Packages.google_api_python_client
    pkgs.python311Packages.google-cloud-language
    pkgs.google-drive-ocamlfuse
    pkgs.emacsPackages.google
    pkgs.python310Packages.googletrans
    pkgs.python311Packages.google-cloud-automl
    pkgs.python311Packages.google-cloud-securitycenter
    pkgs.python311Packages.google-i18n-address
    pkgs.haskellPackages.GoogleCodeJam
    pkgs.haskellPackages.GoogleDirections
    pkgs.perlPackages.GoogleProtocolBuffers
    pkgs.haskellPackages.GoogleSB
    pkgs.haskellPackages.GoogleChart
    pkgs.perl534Packages.GoogleProtocolBuffers
    pkgs.haskellPackages.GoogleSuggest
    pkgs.haskellPackages.GoogleTranslate
    pkgs.perl536Packages.GoogleProtocolBuffers
    pkgs.perlPackages.TestNeeds
    pkgs.megacli
    pkgs.linuxPackages_5_15_hardened.nvidia_x11_beta_open
    pkgs.gvm-tools
    pkgs.civetweb
    pkgs.haskellPackages.hs-gizapp
    pkgs.haskellPackages.highlighter2
    pkgs.gnomeExtensions.dash-to-dock
    pkgs.perlPackages.NetServer
    pkgs.perl536Packages.NetAsyncHTTPServer
    pkgs.perl534Packages.CatalystXScriptServerStarman
    pkgs.perl536Packages.TestHTTPServerSimple
    pkgs.perl534Packages.NetLDAPServer
    pkgs.perl536Packages.HTTPServerSimpleMason
    pkgs.perl536Packages.NetLDAPServer
    pkgs.perl536Packages.NetServerSSPrefork
    pkgs.perl536Packages.CatalystXScriptServerStarman
    pkgs.perl536Packages.HTTPServerSimpleAuthen
    pkgs.perl534Packages.TestHTTPServerSimple
    pkgs.perlPackages.HTTPServerSimpleMason
    pkgs.perlPackages.NetAsyncHTTPServer
    pkgs.haskellPackages.serverless-haskell
    pkgs.haskellPackages.servant-errors
    pkgs.haskellPackages.serversession-frontend-yesod
    pkgs.haskellPackages.server-generic
    pkgs.haskellPackages.serversession
    pkgs.python310Packages.serverlessrepo
    pkgs.haskellPackages.serversession-frontend-snap
    pkgs.haskellPackages.serversession-backend-persistent
    pkgs.nodePackages.serverless
    pkgs.haskellPackages.serversession-frontend-wai
    pkgs.serverspec
    pkgs.haskellPackages.serversession-backend-acid-state
    pkgs.python311Packages.serverlessrepo
    pkgs.haskellPackages.serversession-backend-redis
    pkgs.perl534Packages.ServerStarter
    pkgs.perl536Packages.ServerStarter
    pkgs.perlPackages.ServerStarter
    pkgs.sbclPackages.architecture_dot_builder-protocol_dot_universal-builder
    pkgs.python311Packages.azure-functions-devops-build
    pkgs.python310Packages.azure-functions-devops-build
    pkgs.python310Packages.sphinx-autobuild
    pkgs.python311Packages.sphinx-autobuild
    pkgs.sphinx-autobuild
    pkgs.autobuild
    pkgs.emacsPackages.autobuild
    pkgs.postgresql13Packages.pg_hint_plan
    pkgs.haskellPackages.phonetic-languages-simplified-generalized-examples-common
    pkgs.php80Extensions.intl
    pkgs.php81Extensions.intl
    pkgs.php82Extensions.intl
    pkgs.php81Extensions.filter
    pkgs.php80Extensions.filter
    pkgs.php81Extensions.fileinfo
    pkgs.php82Extensions.filter
    pkgs.php80Extensions.fileinfo
    pkgs.php82Extensions.fileinfo
    pkgs.home-assistant-component-tests.philips_js
    pkgs.rPackages.philentropy
    pkgs.python310Packages.ha-philipsjs
    pkgs.haskellPackages.phizzle
    pkgs.python311Packages.ha-philipsjs
    pkgs.rPackages.philr
    pkgs.rPackages.PhilipsHue
    pkgs.rPackages.kernelPhil
    pkgs.perlPackages.PerlCriticPolicyVariablesProhibitLoopOnHash
    pkgs.perlPackages.PerlIOLayers
    pkgs.perl534Packages.PerlIOviadynamic
    pkgs.perlPackages.PerlCritic
    pkgs.perl534Packages.PerlPrereqScanner
    pkgs.perl536Packages.Perlosnames
    pkgs.perl536Packages.PerlIOeol
    pkgs.perl534Packages.PerlIOutf8_strict
    pkgs.perl536Packages.PerlIOviasymlink
    pkgs.perl536Packages.PerlIOviaTimeout
    pkgs.perl536Packages.PerlDestructLevel
    pkgs.perl536Packages.PerlCriticCommunity
    pkgs.perl534Packages.PerlCritic
    pkgs.perl536Packages.PerlTidy
    pkgs.perlPackages.Perl6Junction
    pkgs.perlcritic
    pkgs.perl534Packages.PerlCriticCommunity
    pkgs.perl534Packages.PerlVersion
    pkgs.perl534Packages.PerlIOLayers
    pkgs.haskellPackages.persistent-database-url
    pkgs.sbclPackages.cl-glfw-opengl-arb__occlusion__query2
    pkgs.python310Packages.pytest-param-files
    pkgs.sbclPackages.cl-glfw-opengl-arb__multisample
    pkgs.sbclPackages.cl-glfw-opengl-arb__color__buffer__float
    pkgs.sbclPackages.cl-glfw-opengl-arb__multitexture
    pkgs.sbclPackages.cl-glfw-opengl-arb__half__float__vertex
    pkgs.python310Packages.pytest-base-url
    pkgs.python311Packages.pytest-base-url
    pkgs.sbclPackages.cl-glfw-opengl-arb__half__float__pixel
    pkgs.sbclPackages.cl-glfw-opengl-arb__shading__language__100
    pkgs.sbclPackages.cl-glfw-opengl-arb__blend__func__extended
    pkgs.sbclPackages.cl-glfw-opengl-arb__shading__language__include
    pkgs.hunspellDicts.es_ANY
    pkgs.hunspellDicts.es-any
    pkgs.hunspellDicts.es-ar
    pkgs.hunspellDicts.es_AR
    pkgs.haskellPackages.shakespeare-babel
    pkgs.python310Packages.pygments-markdown-lexer
    pkgs.haskellPackages.Parallel-Arrows-Multicore
    pkgs.python311Packages.pygments-markdown-lexer
    pkgs.sbclPackages.persistent-variables
    pkgs.haskellPackages.pandoc-linear-table
    pkgs.python310Packages.pyweatherflowrest
    pkgs.perlPackages.PodElementalPerlMunger
    pkgs.perl536Packages.PodElementalPerlMunger
    pkgs.sbclPackages.persistent-variables_dot_test
    pkgs.python311Packages.pyweatherflowrest
    pkgs.perl534Packages.PodElementalPerlMunger
    pkgs.emacsPackages.path-headerline-mode
    pkgs.python310Packages.testrepository
    pkgs.haskellPackages.gi-girepository
    pkgs.python311Packages.testrepository
    pkgs.elasticsearchPlugins.repository-s3
    pkgs.ocamlPackages.opam-repository
    pkgs.elasticsearchPlugins.repository-gcs
    pkgs.emacsPackages.find-file-in-repository
    pkgs.perl534Packages.ModuleInstallRepository
    pkgs.rPackages.FlowRepositoryR
    pkgs.perl536Packages.ModuleInstallRepository
    pkgs.perlPackages.GitRepository
    pkgs.python310Packages.repoze_sphinx_autointerface
    pkgs.python310Packages.repoze_lru
    pkgs.python311Packages.repocheck
    pkgs.python311Packages.repoze_lru
    pkgs.python311Packages.repoze_who
    pkgs.grafana_reporter
    pkgs.python310Packages.repoze_who
    pkgs.reposurgeon
    pkgs.emacsPackages.repology
    pkgs.psc-package
    pkgs.blucontrol
    pkgs.haskellPackages.haskell-packages
    pkgs.haskellPackages.fedora-packages
    pkgs.sbclPackages.org_dot_tfeb_dot_conduit-packages
    pkgs.idris
    pkgs.perlPackages.PackageConstants
    pkgs.xmonad-with-packages
    pkgs.emacsPackages.helm-system-packages
    pkgs.emacsPackages.system-packages
    pkgs.sbclPackages.snark-auxiliary-packages
    pkgs.perl536Packages.PackageConstants
    pkgs.octavePackages.writeRequiredOctavePackagesHook
    pkgs.emacsPackages.list-packages-ext
    pkgs.termonad
    pkgs.taffybar
    pkgs.perl534Packages.PackageConstants
    pkgs.haskellPackages.oden-go-packages
    pkgs.ihaskell
    pkgs.perlPackages.CPAN02PackagesSearch
    pkgs.agda
    pkgs.perl536Packages.CPAN02PackagesSearch
    pkgs.perl534Packages.CPAN02PackagesSearch
    pkgs.perl534Packages.PackageStashXS
    pkgs.perl534Packages.PackageStash
    pkgs.perlPackages.PackageStash
    pkgs.perlPackages.PackageStashXS
    pkgs.perl536Packages.PackageStashXS
    pkgs.perl536Packages.PackageStash
    pkgs.cinnamon.muffin
    pkgs.perl534Packages.SyntaxKeywordJunction
    pkgs.go-dependency-manager
    pkgs.StormLib
    pkgs.haskellPackages.ihaskell-rlangqq
    pkgs.haskellPackages.patch
    pkgs.haskellPackages.cabal-dependency-licenses
    pkgs.haskellPackages.withdependencies
    pkgs.haskellPackages.extract-dependencies
    pkgs.rubyPackages_3_0.cocoapods-dependencies
    pkgs.rubyPackages_2_7.cocoapods-dependencies
    pkgs.rubyPackages.cocoapods-dependencies
    pkgs.rubyPackages_3_2.cocoapods-dependencies
    pkgs.rubyPackages_3_1.cocoapods-dependencies
    pkgs.linuxPackages_zen.phc-intel
    pkgs.haskellPackages.linux-cgroup
    pkgs.pam
    pkgs.linux_xanmod_stable
    pkgs.haskellPackages.linux-capabilities
    pkgs.linux_4_19_hardened
    pkgs.linux-rt_5_15
    pkgs.linuxPackages_latest-libre.kernel
    pkgs.libertine
    pkgs.linux-manual
    pkgs.linux_6_3
    pkgs.linux_6_1_hardened
    pkgs.perl534Packages.LinuxFD
    pkgs.perlPackages.LinuxDistribution
    pkgs.perlPackages.LinuxInotify2
    pkgs.perl536Packages.LinuxDistribution
    pkgs.perl534Packages.LinuxDistribution
    pkgs.perl534Packages.LinuxInotify2
    pkgs.perl534Packages.LinuxDesktopFiles
    pkgs.perlPackages.LinuxFD
    pkgs.perl536Packages.Linuxusermod
    pkgs.perl536Packages.LinuxInotify2
    pkgs.perlPackages.LinuxACL
    pkgs.perlPackages.Linuxusermod
    pkgs.perl534Packages.LinuxACL
    pkgs.perl534Packages.Linuxusermod
    pkgs.perl536Packages.LinuxACL
    pkgs.perl536Packages.LinuxDesktopFiles
    pkgs.perl536Packages.LinuxFD
    pkgs.taktuk
    pkgs.rPackages.PLRModels
    pkgs.python311Packages.safetensors
    pkgs.python311Packages.rjsmin
    pkgs.rPackages.NCA
    pkgs.lispPackages.prove
    pkgs.haskellPackages.fpco-api
    pkgs.haskellPackages.requirements
    pkgs.emacsPackages.reddigg
    pkgs.haskellPackages.shadowsocks
    pkgs.python311Packages.typical
    pkgs.gnomeExtensions.argos
    pkgs.emacsPackages.company-dcd
    pkgs.xorg.fontbh75dpi
    pkgs.rPackages.LinkageMapView
    pkgs.nix-serve-ng
    pkgs.nixVersions.unstable
    pkgs.nix-serve
    pkgs.nix-delegate
    pkgs.haskellPackages.nix-serve-ng
    pkgs.nix-prefetch-docker
    pkgs.nixUnstable
    pkgs.haskellPackages.nixpkgs-update
    pkgs.nix-simple-deploy
    pkgs.nix-plugins
    pkgs.nixVersions.stable
    pkgs.haskellPackages.nix-thunk
    pkgs.python310Packages.nixpkgs-pytools
    pkgs.nixpkgs-hammering
    pkgs.python311Packages.nix-prefetch-github
    pkgs.nixdoc
    pkgs.nix_2_3
    pkgs.haskellPackages.nix-delegate
    pkgs.nix-ld
    pkgs.nix-template-rpm
    pkgs.nix-prefetch-scripts
    pkgs.python310Packages.nix-kernel
    pkgs.python310Packages.nixpkgs
    pkgs.nixos-shell
    pkgs.nix-bisect
    pkgs.nixpkgs-lint
    pkgs.haskellPackages.nixos-types
    pkgs.nix-update
    pkgs.nixos-render-docs
    pkgs.nano
    pkgs.python310Packages.venusian
    pkgs.linuxPackages_latest.vendor-reset
    pkgs.vimPlugins.venn-nvim
    pkgs.linuxPackages_xanmod.vendor-reset
    pkgs.ventoy-bin-full
    pkgs.ventoy-bin
    pkgs.vendir
    pkgs.linuxPackages_6_1_hardened.vendor-reset
    pkgs.linuxPackages_latest-libre.vendor-reset
    pkgs.linuxPackages_5_10_hardened.vendor-reset
    pkgs.linuxPackages_4_19_hardened.vendor-reset
    pkgs.python310Packages.venvShellHook
    pkgs.venta
    pkgs.python311Packages.venstarcolortouch
    pkgs.linuxPackages_5_15_hardened.vendor-reset
    pkgs.linuxPackages_4_14_hardened.vendor-reset
    pkgs.linuxPackages.vendor-reset
    pkgs.linuxPackages-libre.vendor-reset
    pkgs.linuxPackages_hardened.vendor-reset
    pkgs.postgresql15JitPackages.pipelinedb
    pkgs.haskellPackages.pipes-lzma
    pkgs.haskellPackages.pipes-ordered-zip
    pkgs.haskellPackages.pipes-brotli
    pkgs.haskellPackages.pipes-vector
    pkgs.haskellPackages.pipes-conduit
    pkgs.haskellPackages.pipes-bzip
    pkgs.haskellPackages.pipes-safe
    pkgs.haskellPackages.pipes-group
    pkgs.haskellPackages.pipes-interleave
    pkgs.haskellPackages.pipes-attoparsec_0_6_0
    pkgs.haskellPackages.pipes-network
    pkgs.haskellPackages.pipes-network-ws
    pkgs.haskellPackages.pipes-fluid
    pkgs.haskellPackages.pipes-cellular-csv
    pkgs.haskellPackages.pipes
    pkgs.haskellPackages.Pipe
    pkgs.python311Packages.bootstrapped-pip
    pkgs.pipes-rs
    pkgs.python310Packages.pipx
    pkgs.pip-audit
    pkgs.python311Packages.pip
    pkgs.python311Packages.pipdeptree
    pkgs.arcanPackages.pipeworld-wrapped
    pkgs.arcanPackages.pipeworld
    pkgs.emacsPackages.pipenv
    pkgs.python310Packages.pip-api
    pkgs.python311Packages.pip-api
    pkgs.python311Packages.python-telegram-bot
    pkgs.python310Packages.magic
    pkgs.python310Packages.python-heatclient
    pkgs.python311Packages.python-datemath
    pkgs.python311Packages.python-lzf
    pkgs.python311Packages.python-trovo
    pkgs.python310Packages.debian
    pkgs.python310Packages.python-opendata-transport
    pkgs.python310Packages.python-swiftclient
    pkgs.python311Packages.python_simple_hipchat
    pkgs.python310Packages.sigrok
    pkgs.python311Packages.python-ironicclient
    pkgs.python311Packages.python-arango
    pkgs.python311Packages.python-pkcs11
    pkgs.emacsPackages.python-switch-quotes
    pkgs.python310Packages.python_mimeparse
    pkgs.python311Packages.python-smarttub
    pkgs.python311Packages.python3-gnutls
    pkgs.python311Packages.python3-saml
    pkgs.gnuradioPackages.python
    pkgs.python310Packages.python-fontconfig
    pkgs.python311Packages.python-fontconfig
  ];
}